### ISSUE TITLE
fix(normalize): Decimals from string when convert to number

### ISSUE THREAD

**Issue by hammeronthenet** [benjamin-allion/json-node-normalizer#24]
Hi, it seems that if I've a decimal number as string in my json (ie: "Amount":"14333.22"), and then I try to convert it to number, the normalization loses the decimals value.

**Comment by benjamin-allion** [comment]
Thank's for your feedback.
I'll try fix that problem today.

**Comment by hammeronthenet** [comment]
I patched in types.js:

```
case NodeTypes.NUMBER_TYPE:
     return !Number.isInteger(jsonNode) ? parseInt(jsonNode, 10) : jsonNode;
   case NodeTypes.INTEGER_TYPE:
     return !Number.isInteger(jsonNode) ? parseInt(jsonNode, 10) : jsonNode;
```

Number should do a parseFloat imho.

I patched in this manner and it works. ;)

**Comment by benjamin-allion** [comment]
Well done ! 
I'll try to add some tests for that use case.

**Comment by benjamin-allion** [comment]
Done v.1.0.4.
