### ISSUE TITLE
BUG : generating default value of a boolean field even if the value already exists

### ISSUE THREAD

**Issue by elrhourha** [benjamin-allion/json-node-normalizer#52]
BUG : generating default value of a boolean field even if the value already exists.
for example : 
``
> "properties": {
> > "active"{
> >"type": "boolean",
 > >"description": "example",
 > >"default": true,
> >  }
> }
``
**Example :** 

``
const JsonNodeNormalizer = require('json-node-normalizer')
``
``
fieldsClone = await JsonNodeNormalizer.normalize({active : false}, {...})
``
this will generate : 
``
{
active : true
}
``

**Comment by benjamin-allion** [comment]
Done.
